-- Active: 1698301408453@@localhost@5432@wallet
DROP TABLE IF EXISTS "category";

CREATE TABLE IF NOT EXISTS "category" (
    id SERIAL PRIMARY KEY,
    name VARCHAR(250) NOT NULL UNIQUE
);

INSERT INTO "category" (id, name) VALUES
(1, 'Transfert'),
(2, 'Food & Drinks'),
(3, 'Bar, cafe'),
(4, 'Groceries'),
(5, 'Restaurant, fast-food'),
(6, 'Shooping'), 
(7, 'Clothes & shoes'),
(8, 'Drug-store, chemist'),
(9, 'Electronics, accessories'),
(10, 'Free time'),
(11, 'Gifts, joy'),
(12, 'Health and beauty'),
(13, 'Home, garden'),
(14, 'Kids'),
(15, 'Pets, animals'),
(16, 'Stationery, tools'),
(17, 'Housing'), 
(18, 'Energy, utilities'),
(19, 'Maintenance, repairs'),
(20, 'Mortgage'),
(21, 'Property insurance'),
(22, 'Rent'),
(23, 'Services'),
(24, 'Transportation'),
(25, 'Business trips'),
(26, 'Long distance'),
(27, 'Public transport'),
(28, 'Taxi'),
(29, 'Vehicle'),
(30, 'Fuel'),
(31, 'Leasing'),
(32, 'Parking'),
(33, 'Rentals'),
(34, 'Vehicle insurance'),
(35, 'Vehicle maintenance'),
(36, 'Life & Entertaiment'),
(37, 'Active sport, fitness'),
(38, 'Alcohol, tobacco'),
(39, 'Books, audio, subscriptions'),
(40, 'Charity, gifts'),
(41, 'Culture, sport events'),
(42, 'Educations, developmet'),
(43, 'Health car, doctor'),
(44, 'Hobbies'),
(45, 'Holday, trips, hotels'),
(46, 'Life events'),
(47, 'Lottery, gambling'),
(48, 'TV, Streaming'),
(49, 'Wellness, beauty'),
(50, 'Communication, PC'),
(51, 'Internet'),
(52, 'Phone, mobile phone'),
(53, 'Postal services'),
(54, 'Software, apps, games'),
(55, 'Finacial expenses'),
(56, 'Advisory'),
(57, 'Charges, Fees'),
(58, 'Child Support'),
(59, 'Fines'),
(60, 'Insurances'),
(61, 'Loan, intersts'),
(62, 'Taxes'),
(63, 'Investments'),
(64, 'Collections'),
(65, 'Financial investments'),
(66, 'Realty'),
(67, 'Savings'),
(68, 'Vehicle, chattels'),
(69, 'Income'),
(70, 'Lending, renting'),
(71, 'Refunds'),
(72, 'Rental income'),
(73, 'Sale'),
(74, 'Wage, invoices');
